### ISSUE TITLE
Multi stream does not respect top level "level" property

### ISSUE THREAD

**Issue by yunong** [pinojs/pino-multi-stream#10]
We ran into the issue where our logger wasn't respecting the ```level``` property at the top level. I did some testing and it does look like that is the case. Simple repro below:

```javascript
require('pino-multi-stream')({ level: 'debug' }).level
> 'info'
```

cc @retrohacker

**Comment by jsumners** [comment]
@mcollina this bug hits https://github.com/pinojs/pino-multi-stream/commit/72e8cdfb89ebe1d376361e02e41a75602c064850#diff-168726dbe96b3ce427e7fedce31bb0bcL16 in the original code. Your modification for the metadata protocol switched it from running "real Pino" to returning a multistream wrapped instance. Further, the latest code doesn't even account for this case; the options would have to have a `write` property in order for a real Pino instance to be returned.

So what I think is happening is that `fixLevel` is not doing what it claims to do.

**Comment by mcollina** [comment]
https://github.com/pinojs/pino-multi-stream/blob/master/index.js#L29-L35 is triggered only if there is a `streams` property in the options. However, that block of code sets the outer level of pino to the lowest level within a stream. In this case, we need to do the reverse: we need to attach the level of the main pino instance to the one of the (only) stream.

Probably there are more edge cases on these, keep reporting them.

```js
var pino = require('pino-multi-stream')()
pino.level = 'debug'
```

Should work.

**Comment by jsumners** [comment]
Which is why in my original implementation I completely avoided the wrapper unless there were actually multiple streams configured. Basically, the only thing that would trigger the wrapper is `streams` being an instance of `Array`.

**Comment by mcollina** [comment]
@jsumners we do not have a wrapper on pino now, we just have a wrapper around the streams, but this could make the levels out of sync. 
One of the goal is to allow to add streams along the way :(. Or we might remove that feature completely.

**Comment by jsumners** [comment]
I must've missed that. I would vote against being able to add streams after construction. That seems like a lot of work for something I've never heard of anyone doing.

**Comment by yunong** [comment]
Thanks for the quick fix @mcollina, however, it looks like this doesn't work when more than one stream is set in the constructor. This is using the latest 3.1.1

```javascript
> require('pino-multi-stream')({level: 'debug', streams: [{stream: process.stdout}, {stream: process.stderr}]}).level
'info'
```

**Comment by mcollina** [comment]
the default level for any passed stream is info by default, and the level is currently set to the min level across all the streams. 
This is to save some CPU cycles.

I would recommend you to avoid passing a level if you are using multiple streams.
