### ISSUE TITLE
very good solution for compatibility

### ISSUE THREAD

**Issue by volkmarbuehringer** [pinojs/pino-multi-stream#2]
this will solve my problems with bunyan compatibility and pm2 when it is released.

Thank you very much.

**Comment by jsumners** [comment]
It will be released soon. Hopefully you won't stop at using this as your solution. Please pay attention to the caveats section of the readme.

I will close this issue after release.

**Comment by jsumners** [comment]
This module is now published -- https://www.npmjs.com/package/pino-multi-stream
