### ISSUE TITLE
Recreate logfile?

### ISSUE THREAD

**Issue by Elexy** [pinojs/pino-multi-stream#21]
probably by design, but just checking.

I see that the specified logfile is not recreated if it was removed sometime after creation.
I expected it to be recreated if some process would rotate the file for example.
Renaming the file retains it as a destination, though.
```
const util = require('util')
const fs = require('fs')
const fsUnlink = util.promisify(fs.unlink)
const pinoms = require('pino-multi-stream')
const streams = [
  {stream: fs.createWriteStream('/tmp/info.stream.out')},
  {level: 'fatal', stream: fs.createWriteStream('/tmp/fatal.stream.out')}
]
var log = pinoms({streams: streams})

log.info('this will be written to /tmp/info.stream.out')
log.fatal('this will be written to /tmp/fatal.stream.out')

const moveLog = async () => {
  await fsUnlink('/tmp/info.stream.out')
}
moveLog()

log.info('this will NOT be written to /tmp/info.stream.out')
```

**Comment by mcollina** [comment]
Note that the above code does not recreate the file because.. it is still writing to it. There is no logic in your code to close the file descriptor in `createWriteStream` and reopen it. You can use https://github.com/mcollina/sonic-boom#sonicboomreopenfile instead, and it offers that capability.
It's also significantly faster, so hey ;). 

This is covered in https://getpino.io/#/docs/help?id=reopening.

**Comment by brilvio** [comment]
There is a way to reopen the streams using `pino-multi-stream` ? I searched and didn't understand how to reopen. I know how to reopen using only one destination but with multi-stream I am lost.

Sorry if this is not the place to ask this.

**Comment by mcollina** [comment]
You should use https://www.npmjs.com/package/sonic-boom as a stream destination

**Comment by brilvio** [comment]
Thanks, this will solve the problem, yes?
```javascript
streams.forEach(el => {
   el.stream.reopen();
});
```
I

**Comment by mcollina** [comment]
I think so, yes.

Il giorno mer 14 ago 2019 alle 13:31 Fernando Derkoski <
notifications@github.com> ha scritto:
