### ISSUE TITLE
Custom levels don't behave the same with and without pino-multi-stream

### ISSUE THREAD

**Issue by h-Reser** [pinojs/pino-multi-stream#23]
Hello,

I'm creating a pino logger with some custom levels.
This is my code:
```
const pino = require("pino");
const pinoms = require("pino-multi-stream");
const streams = [
   { stream: process.stdout }
];
const logger = pino({
    customLevels: {
      foo: 15,
      bar: 25,
      baz: 35,
      bazz: 45
    },
    level: "bar",
    useLevelLabels: true,
}, pinoms.multistream(streams));
```

When I send logs with level set to `bar`, this is what I get
```
  logger.trace("trace");  // doesn't log --> expected
  logger.foo("foo");      // doesn't log --> expected
  logger.bar("bar");      // doesn't log --> I should have a log
  logger.info("info");    // log --> expected
  logger.baz("baz");     // log --> expected
  logger.bazz("bazz");  // log --> expected
```
When I send logs with level set to `foo`, only `info`, `baz` and `bazz` are logging, which is not normal because I would expect `foo` and `bar` to also log.

Let's say that I change my levels to the following:
```
customLevels: {
      foo: 1,
      bar: 2,
      baz: 3,
      bazz: 4
    }
```
Only `info` will log. My custom levels will never log, whatever I do.

Finally, let's say that I change my levels to the following:
```
customLevels: {
      foo: 100,
      bar: 200,
      baz: 300,
      bazz: 400
    }
```
Here the logger behaves as it should. For example, when setting the level to `foo`, then `foo`, `bar`, `baz` and `bazz` will all log.

If I don't use `pino-multi-stream`, then all the custom levels behave as expected in any of the situations described above.

It seems to me that `pino-multi-stream` doesn't behave correctly for the custom levels which have a value below 30.

**Comment by mcollina** [comment]
By default the streams are configured to output only level >= 30. You’d need to add a level property when you define the stream.

**Comment by h-Reser** [comment]
Thanks for getting back at me.
I tried the code below. Still the same behavior. Is there something else I'm doing wrong?
```
  const pino = require("pino");
  const pinoms = require("pino-multi-stream");
  const streams = [
    { level: "foo", stream: process.stdout }
  ];
  const logger = pino({
    customLevels: {
      foo: 15,
      bar: 25,
      baz: 35,
      bazz: 45
    },
    useLevelLabels: true,
  }, pinoms.multistream(streams));

  logger.trace("trace");  // doesn't log --> expected
  logger.foo("foo");      // doesn't log --> I should have a log
  logger.bar("bar");      // doesn't log --> I should have a log
  logger.info("info");    // log --> expected
  logger.baz("baz");     // log --> expected
  logger.bazz("bazz");  // log --> expected
```

**Comment by mcollina** [comment]
There might be an issue with custom levels. Would you like to work on this and send a PR? We might have to expose some accessors in pino.

**Comment by h-Reser** [comment]
I can try making a PR, yes. Never made any, but I'm sure I will find how to:)

I had a look at the code. It seems that the levels are hardcoded in [multistream.js](https://github.com/pinojs/pino-multi-stream/blob/d60c93164f358e9052f2b87bac33c0bc4b23e888/multistream.js#L5).
I don't see how we can get the custom levels from the pino instance, because pino is not instantiated yet at the time `pino-multi-stream` is called. But then I don't know pino well enough, maybe I'm missing something.

I found a small hack to achieve what I want. It consists of adding a second optional parameter to the `multistream` function.
Then, if I run with this code, it seems to be working as expected.

```
const Pino = require("pino");
const multistream = require("../../../pino-multi-stream").multistream;
const customLevels = {
  foo: 1,
  bar: 2,
  baz: 3,
  bazz: 4
}
const streams = [
  { level: "foo", stream: process.stdout }
];
const logger = Pino({
  customLevels,
  level: "foo", 
  useLevelLabels: true,
  useOnlyCustomLevels: true,
}, multistream(streams, customLevels));

logger.foo("foo");
logger.bar("bar");
logger.baz("baz");
logger.bazz("bazz");
```
Here is the link to my change: [007abf0](https://github.com/h-Reser/pino-multi-stream/commit/007abf04f0778990d88e0329462b5c8f187b8262#diff-e1e164c6eefd5bbfa32b42e115fbfdc1)

Is this the kind of change you'd be willing to consider?

**Comment by mcollina** [comment]
Yes, definitely.

**Comment by ovhemert** [comment]
Change looks fine by me. @h-Reser could you send the PR for this?
Let me know if you need help with that.

**Comment by h-Reser** [comment]
[Done](https://github.com/pinojs/pino-multi-stream/pull/24). Hope it works.
Sorry for the delay, my mind has been slipping elsewhere lately :)

**Comment by ovhemert** [comment]
Did you get a change to look at my [comment](https://github.com/pinojs/pino-multi-stream/pull/24#discussion_r294637798) ?
Please tell me if you do not have the time to look into this, I can take over from here if you want.

**Comment by h-Reser** [comment]
The ci is passing now, thanks for your input.
I tried to make a test this morning, but for some reason the test fails on line 215 of `test/multistream.test.js`. Don't know if it has something to do with my Node.js version (12.4.0), but shouldn't fail since Travis-CI is passing. It will take me a while to figure that out, because I'm barely starting my computer these days.
If you want to take over, fell free to do so. Otherwise, I'll try again to figure that out :)

**Comment by ovhemert** [comment]
No problem, I will have a look at it.

**Comment by ovhemert** [comment]
The error that you encounter on line 215 is related to another issue that came up when adding Node v12 checks. See https://github.com/pinojs/pino-multi-stream/pull/25/commits/dece24618887183ffb7b32dcac1b45024f295fff

If you rebase your branch on top of the updated master, the error will be gone. 
You can also make your test using Node v10, it will not throw the error on you current branch.

**Comment by keyvez** [comment]
I need to use customLevels and route the output to a file, I see there is an existing PR for that. Are you planning to pick it back up?
