### ISSUE TITLE
Passing arguments to prettyStream

### ISSUE THREAD

**Issue by yaskevich** [pinojs/pino-multi-stream#27]
Currently, this method of `pino-multi-stream` looks like this:
`pinoms.prettyStream({ [prettifier], [dest] })`.

But original function is `getPrettyStream (opts, prettifier, dest)`.
So there is no way to pass features object (with features like `translateTime`, `ignore`, `colorize`).
The module just puts an empty object there (`index.js` line 91):

`return getPrettyStream({}, prettifier, dest)`

Could you unify API of original function from `pino\lib\tools` and method of this module?

**Comment by mcollina** [comment]
Would you like to send a PR?

Il giorno sab 27 lug 2019 alle 09:46 Alyaxey Yaskevich <
notifications@github.com> ha scritto:

**Comment by yaskevich** [comment]
Done. #28

**Comment by P4sca1** [comment]
This can be closed as #28 has been merged. @mcollina
