### ISSUE TITLE
Log no longer written to multiple streams

### ISSUE THREAD

**Issue by P4sca1** [pinojs/pino-multi-stream#33]
Im having an issue since version 5.0 that a log only gets written to one destination stream.
Here is my config: 
```ts
const logger = pinoms({
  base: null,
  redact: {
    paths: [
      '*.headers.authorization',
      '*.headers.cookie',
      "*.headers['set-cookie']",
    ],
  },
  streams: [
    // Log everything to stdout in production, prettify in dev environments.
    {
      level: config.logLevel,
      stream:
        process.env.NODE_ENV === 'production'
          ? process.stdout
          : pinoms.prettyStream(),
    },
    // In addition to logging to stdout, capture error and fatal messages with sentry
    { level: 'error', stream: pinoSentryStream },
  ],
})
```

When running `logger.error({ err }, 'Something went wrong')` I expect it to be logged both to stdout and to sentry, but it is only logged to sentry.

**Comment by mcollina** [comment]
Can you please provide a full, running example to reproduce this? Are you sure `pinoSentryStream` does not need an update?

**Comment by P4sca1** [comment]
Weird. Whilte creating a reproduction repo, I noticed that this is working like expected.
Needs to be something else on my end.
