### ISSUE TITLE
Destination write stream file is bloated with NUL characters at head

### ISSUE THREAD

**Issue by thanathip-wisesight** [pinojs/pino-multi-stream#36]
Title.

I use pino-multi-stream with fastify

details

fastify 1.14.6
pino 5.17.0
pino-multi-stream 4.3.0

My app runs in container with mapped volume. There are 2 streams, one is written to a file in the mapped volume, the other is written to std.out of the docker container.

There is only 1 node process.

**Comment by mcollina** [comment]
Can you add an example to reproduce this problem? Thanks.
