### ISSUE TITLE
dedupe logs

### ISSUE THREAD

**Issue by robertsLando** [pinojs/pino-multi-stream#37]
If I have more than one stream I will have multiple logs, for example if one is set to `info` level and the other to `error` the first one will also contain `error` logs, is there a way to prevent this? I mean, if multiple streams are provided, only send those logs to the stream with the higher level only?

**Comment by mcollina** [comment]
There is no such option right now.. I guess a PR would be nice.

**Comment by jsumners** [comment]
The design was merely to provide multiple destinations wherein each destination could have a differing verbosity set. Deduplication was never considered as each destination is technically independent.

**Comment by robertsLando** [comment]
> The design was merely to provide multiple destinations

I know but in my use case (split error levels to `stderr` and others to `stdout`) it is useless and could cause some confusion, also I think in other use cases it could be useful. You should just change the write function in multistream that checks if `dedupe` option is true and if so sends only to the latest matching stream (as the streams are ordered from the lower to the higher)

**Comment by jsumners** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by robertsLando** [comment]
I have tried to implement a PR but there is something I'm missing, some tests are failing. I don't think it would be a big effort for someone who better knows the code to implement such feature, I can send what I have done right now if you want
