### ISSUE TITLE
Not working in browser

### ISSUE THREAD

**Issue by mihai1voicescu** [pinojs/pino-multi-stream#42]
Seem like using this in a browser environment fails due to the deconstruction of a property not found in the pino browser version [here](https://github.com/pinojs/pino-multi-stream/blob/master/index.js#L11).

Any reasons why this shouldn't be used in the browser?

**Comment by jsumners** [comment]
> Any reasons why this shouldn't be used in the browser?

It wasn't designed for such.

**Comment by joshkel** [comment]
For the benefit of anyone else who's searching for information on this issue, here's the exact error:

> TypeError: Cannot destructure property 'streamSym' of 'pino.symbols' as it is undefined.
