### ISSUE TITLE
Stream level changes the level of another stream

### ISSUE THREAD

**Issue by lukassr** [pinojs/pino-multi-stream#43]
Hello,

I'm using multiple streams, and I set the level property for all the streams. The problem I have is, when I change only one child logger level, it changes the another stream I have. 

For example:
```javascript
pinoMultiStream({
    name: 'name',
    level: 'error',
    streams: [
      {
        stream: ringBuffer,
        level: 'debug', 
      },
      {
        stream: process.stdout,
      },
    ],
  });
```

The level of `process.stdout` changes to `debug`, printing all the logs into console. Am I missing some configuration?

Thank you.

**Comment by jsumners** [comment]
Can you provide a full reproduction?

**Comment by lukassr** [comment]
Here's an example:

```javascript
const pinoms = require('pino-multi-stream');
const fs = require('fs');

const logger = pinoms({
  level: 'silent',
  serializers: {
    err: pinoms.stdSerializers.err,
    req: pinoms.stdSerializers.req,
    res: pinoms.stdSerializers.res,
  },
  streams: [
    {
      stream: fs.createWriteStream('./test/info.debug.txt'),
      level: 'debug', 
    },
    {
      stream: fs.createWriteStream('./test/info.silent.txt'),
    },
  ],
});

logger.info('test');

```

It appears that the `debug` level in the child overwrites the `silent` level. If you run that code, you will see a log inside `info.silent.txt`. Also, if you check the level of `logger` it will be `debug` instead of  `silent`.

 I had to fix this putting the level in every child instead of the level in the parent.

**Comment by jsumners** [comment]
Are you looking for the `dedupe` option?

**Comment by lukassr** [comment]
Not really. `dedupe` will only log to the one stream with the higher level. What I'm looking is to have multiple streams, some of them sharing the same level defined in the parent but some others with specific level. In the example above, the second stream should have the `silent` level, because it is declare in the parent, but I think it not the case, because it will log anyways in the .txt. If you declare `level:'silent'` in the second streams, it will work as it should.

Thanks for the answers.

**Comment by jsumners** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.
