### ISSUE TITLE
Provide example how to use standard pino + one more stream

### ISSUE THREAD

**Issue by glensc** [pinojs/pino-multi-stream#55]
I want to use pino in api form (pino + attach prettier), but additionally, add sentry logger:
- https://www.npmjs.com/package/pino-sentry

But all the current examples show that I must create myself default stream:

```js
var streams = [
  {stream: fs.createWriteStream('/tmp/info.stream.out')},
  {level: 'fatal', stream: fs.createWriteStream('/tmp/fatal.stream.out')}
]
var log = pinoms({streams: streams})
```

how to let pino decide the default streams?

```js
const logger = require('pino')()

logger.info('hello world')
```

here it just works, I don't figure out a path for stdout.

**Comment by jsumners** [comment]
The readme should be clear. What is unclear?

**Comment by glensc** [comment]
@jsumners so, how do I create logger without specifying fs.createWriteStream, so it be taken from pino itself? how can you say everything is clear if you don't even understand my question?

**Comment by jsumners** [comment]
https://github.com/pinojs/pino-multi-stream/blob/43aa9d14096e041616a671040c477435c883f005/Readme.md#L58-L60

Provide `process.stdout` as a stream if that is a stream you want to write to.

**Comment by glensc** [comment]
So, the there lacks this from readme:

> To log to the same stream as `pino`, use `process.stdout`.

I have not reverse engineered `pino` source code to see where it logs by default. And so should not do any other newcomer to this package.

**Comment by jsumners** [comment]
Would you like to send a Pull Request to address this issue?

**Comment by glensc** [comment]
@jsumners no

**Comment by glensc** [comment]
Looks like it's more complicated.

```ts
  const logger = pino({
      prettyPrint: {
        colorize: true,
        ignore: 'pid,hostname,time',
      },
    });
```

this translated to multi-stream, first pick would be

```ts
  const logger = pinoms({
      streams,
      prettyPrint: {
        colorize: true,
        ignore: 'pid,hostname,time',
      },
    });
```

however, that results in pretty bad error with no context:

```
node_modules/pino/lib/levels.js:90
  if (values[level] === undefined) throw Error('unknown level ' + level)
                                         ^
```

it appears that the `prettyPrint` key causes the offension:

```
  const logger = pinoms({
      streams,
      prettyPrint: {
      },
    });
```

and this "unknown level" was already reported by some other user, but never fixed.

so appears that pino + pretty print should be used as prettyStream instead:

```ts
  const logger = pinoms({
      streams: [
            stream: pinoms.prettyStream(),
      ],
    });
```

what could be improved in the readme, is provide compact example in top of the readme. for both cases. probably there are more of them, as I've never used this library before.

**Comment by glensc** [comment]
> @jsumners closed this 4 minutes ago

such impatience, and requiring newcomers to do all the job, makes very bad taste in the mouth of the community, I will definitely not recommend pino ecosystem to any of my friends. I think I will just stop even trying to integrate it further.
