### ISSUE TITLE
multilog

### ISSUE THREAD

**Issue by basaran** [pinojs/pino-multi-stream#82]
Hi, thank you for pino-multi-stream and your thoughtful warning about the multiple destinations. I came across the tool called multilog, and wanted to ask you if you have any opinions about it? It seems to work well.

https://cr.yp.to/daemontools/multilog.html

It can be started like this:

```
node src/bin/server.js | tee out >(multilog '-*' '+*"level":30*' ./log/info '-*' '+*"level":50*' ./log/other)      
```

and after further digging, I have also found a go rewrite that is modern and that can work with promtail to ship the logs and also log to syslog.

```
https://github.com/UweOhse/multislog
```

**Comment by mcollina** [comment]
The concern is the same for me. The log processing will move at the speed of the slowest destination.
